---
- name: Install Apache HTTP Server
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start and Enable Apache Service
      service:
        name: apache2
        state: started
        use: "/usr/sbin/service"
