---
- name: Setup Network Services using Ansible
  hosts: servers
  remote_user: root
  become: true
  vars:
    # Variables for network configuration
    dns_primary: 8.8.8.8
    dns_secondary: 8.8.4.4

  tasks:
    - name: Configure DNS settings using shell command
      shell: |
        echo -e 'nameserver {{ dns_primary }}
        nameserver {{ dns_secondary }}' > /etc/resolv.conf
      notify: Restart network

    # Setup IP Routing (Optional Example)
    - name: Configure static route
      lineinfile:
        path: /etc/sysconfig/network-scripts/route-eth0
        line: '10.10.20.0/24 via 192.168.1.1 dev eth0'
        create: yes

  handlers:
    - name: Restart network
      service:
        name: NetworkManager
        state: restarted