---
- name: Install Apache on Web Servers
  hosts: webservers
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

